### ISSUE TITLE
How to customize  dx-tab item

### ISSUE THREAD

**Issue by artstalker** [DevExpress/devextreme-angular#442]
Hi Everyone,

I want to add little X button at the top right corner of every dx-tab item. When a user clicks on it, the tab is closed.

But I have a problem with positioning it at top right corner because dx-template-wrapper uses block-inline style and I don't have all the space of the tab to put it there.
![plunker - google chrome 2017-04-25 18 35 45](https://cloud.githubusercontent.com/assets/2846956/25394153/2315b6b8-29e6-11e7-858b-ee96597b7e2a.png)

Look at my plunker:
http://plnkr.co/edit/HnufVj45PHKSjP78IE2x?p=preview

Do you have any suggestions?

**Comment by GoshaFighten** [comment]
You can remove the default padding for a tab and set only the left and bottom padding:

``` CSS
.dx-tab {
  padding: 0;
  padding-bottom: 9px;
  padding-left: 9px;
}
.dx-tab-content {
  width: 100%;
}
```

This will remove the empty space on top and right. Then, you can center the tab text vertically using the following markup and CSS:

``` HTML
<span class="tab">{{c.text}}</span>
<dx-button text="X"
           (onClick)="deleteTab(c.text)"
           style="padding:0;margin: 0;float: right;">
</dx-button>
```

``` CSS
.tab {
  position: relative;
  top: 6px;
}
```

See the [Plunker](http://plnkr.co/edit/tm28LLvCFfwhP80w9bF5?p=preview) that illustrates this. If this does not meet your requirements, open a new Support Center [ticket](https://www.devexpress.com/Support/Center/Question/Create) for this issue.
